// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2YeTixLY3mCiYmLzUE9TB-KohNh6yxzI',
    appId: '1:1000677623267:web:3d2c2184bbdb46403b4cd6',
    messagingSenderId: '1000677623267',
    projectId: 'hello-creactifs',
    authDomain: 'hello-creactifs.firebaseapp.com',
    storageBucket: 'hello-creactifs.appspot.com',
    measurementId: 'G-ERDY7HC62E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrNk0-f2kTtPvCjhesTgbpqkot8_uqcTo',
    appId: '1:1000677623267:android:028f0580b5d627e23b4cd6',
    messagingSenderId: '1000677623267',
    projectId: 'hello-creactifs',
    storageBucket: 'hello-creactifs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGOSTGgm62dCRYt0no7Sj3G92mLqXY1qs',
    appId: '1:1000677623267:ios:91abbbf553409cc13b4cd6',
    messagingSenderId: '1000677623267',
    projectId: 'hello-creactifs',
    storageBucket: 'hello-creactifs.appspot.com',
    iosBundleId: 'org.numediart.helloCreactifs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGOSTGgm62dCRYt0no7Sj3G92mLqXY1qs',
    appId: '1:1000677623267:ios:1c641719e665bd843b4cd6',
    messagingSenderId: '1000677623267',
    projectId: 'hello-creactifs',
    storageBucket: 'hello-creactifs.appspot.com',
    iosBundleId: 'org.numediart.helloCreactifs.RunnerTests',
  );
}
